[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"
default-run = "day5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { git="https://github.com/manpat/common-rs.git", ref="068bdc3" }